"""New Migration

Revision ID: dac02b558dc4
Revises: 
Create Date: 2021-09-29 08:10:41.460527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dac02b558dc4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conservation_area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('photos_path', sa.String(), nullable=True),
    sa.Column('region_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conservation_area_id'), 'conservation_area', ['id'], unique=False)
    op.create_table('tourist_destination',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('schedule', sa.String(), nullable=True),
    sa.Column('fare', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('recommendation', sa.String(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('hikes', sa.String(), nullable=True),
    sa.Column('photos_path', sa.String(), nullable=True),
    sa.Column('is_beach', sa.Boolean(), nullable=True),
    sa.Column('is_forest', sa.Boolean(), nullable=True),
    sa.Column('is_volcano', sa.Boolean(), nullable=True),
    sa.Column('is_mountain', sa.Boolean(), nullable=True),
    sa.Column('conservation_area_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conservation_area_id'], ['conservation_area.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tourist_destination_id'), 'tourist_destination', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tourist_destination_id'), table_name='tourist_destination')
    op.drop_table('tourist_destination')
    op.drop_index(op.f('ix_conservation_area_id'), table_name='conservation_area')
    op.drop_table('conservation_area')
    # ### end Alembic commands ###
