"""New Migration

Revision ID: e81a6eb99317
Revises: 4237d4b5d8fa
Create Date: 2021-10-04 06:11:58.333528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e81a6eb99317'
down_revision = '4237d4b5d8fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
